// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmwTHCId-xqBkd3s9s6MFzIgcjQwtLxOs',
    appId: '1:906942057916:web:44723389e0d9e6050eefb9',
    messagingSenderId: '906942057916',
    projectId: 'navcet',
    authDomain: 'navcet.firebaseapp.com',
    databaseURL: 'https://navcet-default-rtdb.firebaseio.com',
    storageBucket: 'navcet.appspot.com',
    measurementId: 'G-XNDTM9R784',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcb0vj2pXOy6Wiba0rVvXpUkH2WXFKMkc',
    appId: '1:906942057916:android:d691a603025112ac0eefb9',
    messagingSenderId: '906942057916',
    projectId: 'navcet',
    databaseURL: 'https://navcet-default-rtdb.firebaseio.com',
    storageBucket: 'navcet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKV2_VtR_LrNhO-FPmqn5mZdxaK8MmbBs',
    appId: '1:906942057916:ios:33bad48df1f1d1860eefb9',
    messagingSenderId: '906942057916',
    projectId: 'navcet',
    databaseURL: 'https://navcet-default-rtdb.firebaseio.com',
    storageBucket: 'navcet.appspot.com',
    iosBundleId: 'com.example.trialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKV2_VtR_LrNhO-FPmqn5mZdxaK8MmbBs',
    appId: '1:906942057916:ios:4863dc4d193dc0230eefb9',
    messagingSenderId: '906942057916',
    projectId: 'navcet',
    databaseURL: 'https://navcet-default-rtdb.firebaseio.com',
    storageBucket: 'navcet.appspot.com',
    iosBundleId: 'com.example.trialApp.RunnerTests',
  );
}
